### ISSUE TITLE
cpos and pos switched?

### ISSUE THREAD

**Issue by bastings** [elikip/bist-parser#1]
Hi there and thanks for the great work on this parser! :-) 
I noticed that in utils.py in read_conll and write_conll the CPOS and POS tags switched compared to the data format, i.e. judging from the [CONLL format](http://ilk.uvt.nl/conll/#dataformat) in position 4 is CPOS and position 4 is POS, whereas in the code this is the other way around. Am I missing something?

**Comment by dsindex** [comment]
@bastings you can check this issue 
https://github.com/tensorflow/models/issues/118

it made for conll-u format of universal treebank.
not like conll format which has cpos and pos, 
conll-u format consists of upos and xpos( xpos can have multiple mapping to upos).
i think convert.py is not nessesary when you are using conll format.

**Comment by elikip** [comment]
Just fixed this switch between cpos and pos. Thanks @bastings for your input.
