### ISSUE TITLE
boost::archive::archive_exception with dynet v1.1 for barchybrid  parser

### ISSUE THREAD

**Issue by BhaskarNallani** [elikip/bist-parser#16]
Hi,
I am getting this boost error when I run the barchybrid parser with dynet v1.1.

Does any one faced it? I added few checks in the load input model function but still it is throwing error.
In the legacy code it is working right (with cnn_v1 and earlier version of the parser)

Calling self.model.load(filename) Test/bestarchybrid4B.model
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
./run.sh: line 1: 79790 Aborted                 python parser.py --predict --outdir Test/Output --model Test/bestarchybrid.model --test Test/test.conll --extrn Test/sskip.100.vectors --param Test/bestarchybrid.params

Can some one help me here.
Thank you in advance.

Regards,
Bhaskar

**Comment by brombach** [comment]
Just encountered the exact same issue.
```
$ python src/parser.py --predict --outdir out --test lines.conll09 --extrn sskip.100.vectors --model model/bestarchybrid.model --params model/bestarchybrid.params 
[dynet] random seed: 2452240257
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Using external embedding: sskip.100.vectors
Load external embedding. Vector dimensions 100
libc++abi.dylib: terminating with uncaught exception of type boost::archive::archive_exception: input stream error
Abort trap: 6
```

**Comment by BhaskarNallani** [comment]
Hi,
I am able to run the parser with v1.1 dynet branch with cuDNNV5.1 and with out CUDA backup also.
The issue is in the model file barchybrid.model which is dumped with different version of boost and dynet v1.1 is compatible with boost_1_63_0 only (this if figured it out with after experimenting with 1.58,1.63 and 1.64). I gain ran the training on the development.conll data for 30 epochs and used the generated model for inference. I know this may not perform well on the new data because of less input data to trainer. But my object is not the accuracy here but accelerating it.
-Bhaskar
