### ISSUE TITLE
Transition-based model fails to load

### ISSUE THREAD

**Issue by kwhumphreys** [elikip/bist-parser#2]
The barchybrid parser gives the error:
```
Assertion failed: (nlp == (int)lookup_params.size()), function load, file /Users/kevin/bist/cnn/cnn/model.h, line 138.
```
with the transition-based model linked from the README:
```
-rw-r--r-- 1 kevin staff 813625695 May 20 11:45 bestarchybrid.model
-rw-r--r-- 1 kevin staff   9085191 May 25 11:12 bestarchybrid.params
```

The bmstparser runs without error with the graph-based model linked from the README.

**Comment by elikip** [comment]
Did you give the external embeddings file as parameter too? (you have a link to it from the readme)

**Comment by kwhumphreys** [comment]
Thanks! I missed that Note.
