### ISSUE TITLE
Example training.conll, development.conll, and test.conll files?

### ISSUE THREAD

**Issue by lonnietc** [elikip/bist-parser#3]
Hello,

I have been trying to set up a simple test just to see if the code works but cannot figure out proper training.conll, development.conll, and test.conll files.

Can you please add an example or data directory with these files that you have used to train and test the network as I would like to run the exact replica of your work to get a better feel for it and for the discussions in your paper that I have on BiLSTM parsing for NLP.

If you could please add these files that you used to the repository then that would be a great help in this effort.

Thanks,
Lonnie

**Comment by elikip** [comment]
Unfortunatly, I cannot release the data you requested since it is protected by a commercial license  and therefore conflicts with the apache license.. Regarding the sample conll please refer to the link describing the conll format, there you will be able to find an example conll.

**Comment by shaficse** [comment]
Dear sir , I have also made it workable , code is working well. I used conll format training and development data ... but one thing is not clear to me that .. what should the way to fit test data .. either these will be plain text or not. Sir could you please make me clear . Thank you.
