### ISSUE TITLE
Different results when HEAD and DEPREL columns are removed

### ISSUE THREAD

**Issue by sivareddyg** [elikip/bist-parser#4]
Hi Eliyahu,

Thanks for the sharing the code. I trained your model on UD English, and during test time, I get different results in two different settings.

Setting 1: When gold HEAD and DEPREL columns are present in the test input

> LA: 0.929 
> UAS: 0.88
> LAS: 0.855

Setting 2: When gold HEAD and DEPREL columns are removed from the test input

> LA: 0.89
> UAS: 0.847
> LAS: 0.805

Do you know why is this the case? Is your number on PTB in Setting 1 or 2? 

To give you more details, I evaluate the CONLL output your parser produced against the gold test using MaltEval. 

Thanks a lot,
Siva

**Comment by elikip** [comment]
There should not be any difference between the two.. Can you provide more information so that I can recreate this on my environment?

**Comment by sivareddyg** [comment]
I found the error. In Setting 1, I am providing gold POS tags, and in Setting 2, I am providing predicted POS tags. And obviously, Setting 1 is superior. Sorry for the trouble. The issue is resolved, and it is due to my stupid ignorance. 

Thanks for prompt reply. Please close the issue.
