### ISSUE TITLE
PyCNN link not functional

### ISSUE THREAD

**Issue by msharmavikram** [elikip/bist-parser#6]
Hi, 

https://github.com/clab/cnn/tree/master/pycnn 

This above link needs to be replaced with https://github.com/clab/dynet. pycnn is now updated as DyNet

Thanks
VIkram

**Comment by elikip** [comment]
DyNet is not compatible with the previous version of pycnn used to develop this project, so I updated the link to refer to the new location of the old version (named cnn v1) . I think this should work.
