### ISSUE TITLE
Add support for CoNLL-U data format

### ISSUE THREAD

**Issue by ftyers** [elikip/bist-parser#8]
For compatibility with the Universal Dependencies treebanks, it would be great if bistparser could support the CoNLL-U data format[1], natively through a command line option. The format is almost identical to CoNLL-09 except for some column names are different, and:

* Leave comments in the output
* Skip segmentation spans like `2-4`
```
2-4 dámelo
2    da
3    me
4    lo
```
* And empty node spans like `5.1`
```
1      Sue       Sue
2      likes     like
3      coffee    coffee
4      and       and
5      Bill      Bill
5.1    likes     like
6      tea       tea
```

1. http://universaldependencies.org/format.html

**Comment by dsindex** [comment]
i made a test code for `bist-parser` to train UD treebanks.

https://github.com/dsindex/bist-parser

# apply convert.py

**Comment by ftyers** [comment]
Writing a conversion script would be one way of doing it, but I think a better way is to integrate the functionality natively, perhaps with a commandline switch `--conllu`. If you're doing a lot of work with dependency parsers (SyntaxNet, UDpipe, Bist, MST, Malt) it is really convenient if you don't have to have a suite of conversion scripts and you can just expect them to input/output the (now increasingly standard) CoNLL-U format. :)

**Comment by elikip** [comment]
Thank you for your detailed request and interest in BIST Parser. I have added support of conll-u format in the graph-based parser for now (the transition-based parser will be upgraded soon too). Could please check if it is working ok on your end? (Simply pass the conll-u files instead of the old conll file. The graph-based parser can now parse both conll and conll-u formats seamlessly).

**Comment by ftyers** [comment]
Thanks! Your way of dealing with it is much more elegant than mine was going to be :) 

I tried it, it seems like there are still some problems:

```
$ python src/parser.py --dynet-seed 123456789 --outdir /tmp --train ~/data/ud-treebanks-conll2017/UD_Finnish/fi-ud-train.conllu --dev ~/data/ud-treebanks-conll2017/UD_Finnish/fi-ud-dev.conllu --epochs 30 --lstmdims 125 --lstmlayers 2 --bibi-lstm
[dynet] random seed: 123456789
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Using external embedding: None
Preparing vocab
Traceback (most recent call last):
  File "src/parser.py", line 57, in <module>
    words, w2i, pos, rels = utils.vocab(options.conll_train)
  File "/home/UT/source/bist-parser/bmstparser/src/utils.py", line 34, in vocab
    for sentence in read_conll(conllFP):
  File "/home/UT/source/bist-parser/bmstparser/src/utils.py", line 54, in read_conll
    tokens.append(ConllEntry(int(tok[0]), tok[1], tok[2], tok[4], tok[3], tok[5], int(tok[6]) if tok[6] != '_' else -1, tok[7], tok[8], tok[9]))
ValueError: invalid literal for int() with base 10: 'Symb'
```

This diff seems to fix the problem:

```
$ git diff
diff --git a/bmstparser/src/utils.py b/bmstparser/src/utils.py
index 52bbf79..e9efff7 100644
--- a/bmstparser/src/utils.py
+++ b/bmstparser/src/utils.py
@@ -43,12 +43,12 @@ def read_conll(fh):
     root = ConllEntry(0, '*root*', '*root*', 'ROOT-POS', 'ROOT-CPOS', '_', -1, 'rroot', '_', '_')
     tokens = [root]
     for line in fh:
-        tok = line.strip().split()
-        if not tok:
+        tok = line.strip().split('\t')
+        if not tok or line.strip() == '':
             if len(tokens)>1: yield tokens
             tokens = [root]
         else:
-            if tok[0] == '#' or '-' in tok[0] or '.' in tok[0]:
+            if line[0] == '#' or '-' in tok[0] or '.' in tok[0]:
                 tokens.append(line.strip())
             else:
                 tokens.append(ConllEntry(int(tok[0]), tok[1], tok[2], tok[4], tok[3], tok[5], int(tok[6]) if tok[6] != '_' else -1, tok[7], tok[8], tok[9]))
```

I think the problem is because `.split()` splits on both tabs and spaces and CoNLL-U only allows tabs as column delimiters.

**Comment by elikip** [comment]
Thanks! I integrated the diff you suggested and I hope it is working now. I will apply the same changes to the transition-based parser, and hopefully you could use it with conll-u data very soon.

**Comment by elikip** [comment]
Added conll-u support for transition-based parsing too.. 
It seems to be working on my end. I would appreciate if you could check if it is working for you too.
Thanks again!

**Comment by ftyers** [comment]
Great, thanks! :) I've just checked it and it seems to be working fine (at least it's training). I'll train a whole model and get back to you when I've tested it end to end.

**Comment by ftyers** [comment]
The model trains fine, I get some errors with the eval script.

```
Use of uninitialized value $head_g in string eq at src/utils/eval.pl line 1456, <SYS> line 39536.
Use of uninitialized value $head_g in numeric le (<=) at src/utils/eval.pl line 1462, <SYS> line 39536.
Use of uninitialized value $head_s in string eq at src/utils/eval.pl line 1465, <SYS> line 39536.
Use of uninitialized value $head_s in string eq at src/utils/eval.pl line 1469, <SYS> line 39536.
Use of uninitialized value $head_s in numeric le (<=) at src/utils/eval.pl line 1475, <SYS> line 39536.
Argument "joka" isn't numeric in numeric le (<=) at src/utils/eval.pl line 1462, <SYS> line 39630.
Argument "joka" isn't numeric in numeric le (<=) at src/utils/eval.pl line 1475, <SYS> line 39630.
Use of uninitialized value $head_g in string ne at src/utils/eval.pl line 1446, <SYS> line 39630.
Use of uninitialized value $head_s in string ne at src/utils/eval.pl line 1446, <SYS> line 39630.
Use of uninitialized value $dep_g in string ne at src/utils/eval.pl line 1447, <SYS> line 39630.
Use of uninitialized value $dep_s in string ne at src/utils/eval.pl line 1447, <SYS> line 39630.
Use of uninitialized value $head_g in string eq at src/utils/eval.pl line 1452, <SYS> line 39630.
```

The prediction also seems to work fine:

```
$ wc -l ~/data/ud-treebanks-conll2017/UD_Finnish/fi-ud-dev.conllu
22403 /home/UT/data/ud-treebanks-conll2017/UD_Finnish/fi-ud-dev.conllu
$ wc -l /tmp/test_pred.conll
22403 /tmp/test_pred.conll
```

**Comment by elikip** [comment]
I changed the eval script for conll-u from the old eval script to the new script used by the conll 2017 shared task. The error messages you experienced should disappear now.

**Comment by mdelhoneux** [comment]
All works on my end :) I had to hack the transitions to disallow multiple roots (see multiple root issue #10) so that the ud eval does not fail but all else works fine! Elegant solution as Fran said :)
